### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by joonasil** [organize/Jarmo-s-Syndrome#1]
#### ‎projekti ladattu 05.02.‎2016, ‏‎15:01:05

Hei! Projekti näyttää lähteneen hyvin käyntiin. Testit menevät läpi, mutta hyvin harvoja luokkia on tähän mennessä testattu. En saanut itse ohjelmaa pyörimään (valitti ainakin puutuvasta .mp3 tiedostosta?) eikä ollut aikaa ruveta debuggaamaan mistä johtui joten en pystynyt kuin selaamaan luokkia läpi. Luokat ja pakkaukset on nimetty selkeästi ja ohjelman rakenne tuntuu loogiselta (toki itse intistä johtuneen vuoden ohjelmointi tauon takia olen vähän pihalla interfaceista ym ´:D) ja helposti laajennettavalta ja hallittavalta.

**Comment by organize** [comment]
Hei! Kiitos palautteesta!

Testejä on laajennettu tänään, aikasemmin niitä oli tosiaan jopa kolme :smile:.

Kiitos huomiosta, ettei zip-versio lähde käyntiin. Jostain syystä `resources`-kansio (jossa mm. grafiikkaa ja äänitiedostoja) ei löytänyt pakettiin mukaan, eli pitää korjata tämäkin.
