### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by jtak** [organize/Jarmo-s-Syndrome#2]
# Projekti ladattu 19.02.2016 n. klo 20.

Valitettavasti en saanut ohjelmaa pyörimään, herjasi title.mp3-tiedostosta. Resources-kansio tuli mukana, mutta purkaminenkaan ei auttanut enkä kiireessä ehtinyt alkaa tutkimaan asiaa. Harmi, koska olisin halunnut kokeilla peliä, idea vaikutti mielenkiintoiselta ja koodin perusteella näyttäisi siltä että projekti on jo pitkällä.

Koodista:
* Koodi on selkeää ja siistiä ja fiksusti ryhmiteltyä.
* Käyttöliittymässä pari vähän pidempää metodia, mutta nekin olivat selkeän oloisia. 
* Ohjelma on jaettu perusteellisesti paketteihin, mikä varmasti helpottaa laajennettavuutta. Tällä hetkellä paketteja tuntui olevan ehkä turhankin monta, joidenkin luokkien löytäminen oli vähän hankalaa.
* Paketit on nimetty kuvaavasti, tosin ui.impl ja logic.conc eivät ihan avautuneet. Varmasti auttaisi jos olisin ehtinyt perehtyä koodiin paremmin

**Comment by organize** [comment]
Kiitos katselmoinnista!

Selventääkseni `conc` ja `impl`: `concurrent` ja `implementation`. Eli esim. ui-paketin impl sisältää SyndromeGUI:n toteuttavia luokkia ja niin edelleen. Voisin yrittää tuoda tämän esille paremmin.
